# Generated by Django 5.2.8 on 2025-11-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='forgotpassword',
            table='forgot_password',
        ),
    ]
